const shopActionTypes = {
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE'
};

export default shopActionTypes;
